#!/bin/bash
shopt -s nullglob; for file in *.html; do [[ ! -e "../$file" ]] && cp "$file" "../$file"; done; for file in *.html; do [[ -e "../$file" && "$file" -nt "../$file" ]] && cp "$file" "../$file"
